--- #YAML:1.0
name:               Lexical-Failure
version:            0.000002
abstract:           User-selectable lexically-scoped failure signaling
author:
    - Damian Conway <DCONWAY@CPAN.org>
license:            artistic2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Hash::Util::FieldHash:  0
    Keyword::Simple:      0
    PadWalker:            0
    perl:                 5.014
    Scope::Upper:         0
    Test::Effects:        0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
